# Generated by Django 5.2.4 on 2025-08-01 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_email", models.EmailField(max_length=254)),
                ("to", models.TextField()),
                ("cc", models.TextField(blank=True, null=True)),
                ("bcc", models.TextField(blank=True, null=True)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("attachment", models.BinaryField(blank=True, null=True)),
                (
                    "attachment_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "attachment_content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
