# Generated by Django 5.2.4 on 2025-08-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_sentemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticecompliance",
            name="action_to_be_taken",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="noticecompliance",
            name="date_of_receipt",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="noticecompliance",
            name="description_of_work",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="noticecompliance",
            name="mode_of_receipt",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
