# Generated by Django 5.2.4 on 2025-08-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_noticecompliance_action_to_be_taken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticecompliance",
            name="bill_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
