# Generated by Django 5.2.4 on 2025-08-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_noticecompliance_bill_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticecompliance",
            name="asy",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
