# Generated by Django 5.2.4 on 2025-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_noticecompliance_asy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmaster",
            name="nature_of_client",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bank", "Bank"),
                    ("Government", "Government"),
                    ("HUF", "HUF"),
                    ("Insurance company", "Insurance company"),
                    ("LLP", "LLP"),
                    ("Other", "Other"),
                    ("Partnership firm", "Partnership firm"),
                    ("Private company", "Private company"),
                    ("Proprietorship", "Proprietorship"),
                    ("Public company", "Public company"),
                    ("Trust", "Trust"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
